### ISSUE TITLE
Everytime you change&deploy flowcontrolOut, it will output msg n+1 times

### ISSUE THREAD

**Issue by aabluedragon** [calkoe/node-red-contrib-flowcontrol#2]
Reproduce instructions:
connect an inject node to flowcontrolIn
connect an flowcontrolOut (same topic as flowcontrolIn) to debug node
click deploy.

Change any property (no matter which) on flowcontrolOut, click deploy.
click inject, you will get 2 debug messages.
if you repeat you will get 3..4.. and so on.

**Comment by calkoe** [comment]
Hi aabluedragon,

i can't reproduce your issue.
Please get the latest Version and try again.

**Comment by calkoe** [comment]
Found the issue, there was a Problem with multiple subscriptions to JS-Events.
Fixed this in the latest version.
